management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

  endpoint:
    health:
      show-components: always
#  endpoints:
#    web:
#      exposure:
#        include: "*"

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true